import { useState, useEffect } from 'react'
import api from '../services/api'

export default function ReportsPage() {
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const res = await api.get('/api/v1/reports')
        setReport(res.data)
      } catch (err) {
        console.error(err)
      } finally {
        setLoading(false)
      }
    }
    fetchReport()
  }, [])

  return (
    <div className="space-y-6">
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs">
        <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Reports & Analytics</h1>
        <p className="text-sm text-slate-500 mt-0.5">Aggregated pipeline and financial summaries generated by MongoDB Atlas.</p>
      </div>

      {loading ? (
        <div className="bg-white p-8 rounded-2xl border border-slate-200 text-center text-slate-400 text-xs">
          Loading report metrics...
        </div>
      ) : (
        <div className="space-y-6">
          {/* Summary KPIs */}
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs">
              <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Total Customers</span>
              <p className="mt-2 text-2xl font-bold text-slate-900">{report?.summary?.totalCustomers || 0}</p>
            </div>
            <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs">
              <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Total Leads</span>
              <p className="mt-2 text-2xl font-bold text-blue-600">{report?.summary?.totalLeads || 0}</p>
            </div>
            <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs">
              <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Total Deals</span>
              <p className="mt-2 text-2xl font-bold text-emerald-600">{report?.summary?.totalDeals || 0}</p>
            </div>
            <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-xs">
              <span className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Invoices Issued</span>
              <p className="mt-2 text-2xl font-bold text-violet-600">{report?.summary?.totalInvoices || 0}</p>
            </div>
          </div>

          {/* Breakdown cards */}
          <div className="grid gap-6 md:grid-cols-2">
            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-4">
              <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider">Leads by Status</h3>
              <div className="space-y-2">
                {report?.leadsByStatus?.length > 0 ? (
                  report.leadsByStatus.map((item) => (
                    <div key={item._id} className="flex items-center justify-between p-3 rounded-xl bg-slate-50 border border-slate-100 text-xs">
                      <span className="font-semibold text-slate-800">{item._id || 'Unassigned'}</span>
                      <span className="px-2.5 py-1 rounded-full bg-blue-50 text-blue-700 font-semibold border border-blue-200">
                        {item.count} leads (${Number(item.totalValue || 0).toLocaleString()})
                      </span>
                    </div>
                  ))
                ) : (
                  <p className="text-xs text-slate-400">No leads recorded yet.</p>
                )}
              </div>
            </div>

            <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-4">
              <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider">Deals by Stage</h3>
              <div className="space-y-2">
                {report?.dealsByStage?.length > 0 ? (
                  report.dealsByStage.map((item) => (
                    <div key={item._id} className="flex items-center justify-between p-3 rounded-xl bg-slate-50 border border-slate-100 text-xs">
                      <span className="font-semibold text-slate-800">{item._id}</span>
                      <span className="px-2.5 py-1 rounded-full bg-emerald-50 text-emerald-700 font-semibold border border-emerald-200">
                        {item.count} deals (${Number(item.totalAmount || 0).toLocaleString()})
                      </span>
                    </div>
                  ))
                ) : (
                  <p className="text-xs text-slate-400">No deals in pipeline.</p>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
